main:
  params: [args]
  steps:
    - init:
        assign:
          - processor_url: ${default(map.get(args, "processor_url"), "https://procesamiento-inteligente-596193848439.us-south1.run.app")}
          - processor_audience: ${processor_url}
          - folder_prefix: ${args.folder_prefix}
          - preavaluo_id: ${default(map.get(args, "preavaluo_id"), text.split(folder_prefix, "/")[0])}
          - exec_id: ${sys.get_env("GOOGLE_CLOUD_WORKFLOW_EXECUTION_ID")}

    - callProcessor:
        try:
          call: http.post
          args:
            url: ${processor_url}
            auth:
              type: OIDC
              audience: ${processor_audience}
            headers:
              Content-Type: "application/json"
            body:
              preavaluo_id: ${preavaluo_id}
              folder_prefix: ${folder_prefix}
              workflow_execution_id: ${exec_id}
          result: resp
        retry: ${http.default_retry}

    - done:
        return: ${resp.body}
